on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_TOKEN }}"
        project-url: "https://github.com/vidiabtc/dashboard-github/projects/1"
        column-name: "New"
        label-name: "new"
        columns-to-ignore: ""
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GH_TOKEN }}"
        project-url: "https://github.com/vidiabtc/dashboard-github/projects/1"
        column-name: "In progress"
        label-name: "In progress"
        columns-to-ignore: ""
