name: "Issue Column Change Label"
on:
  project_card:
    types:
      - moved
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "add project status and phase tags"
        uses: andymckay/labeler@master
        if: "${{ github.event.project_card.column_id == '19053080' }}"
        with:
          add-labels: 'Application Phase, Initial Review in Progress'
          repo-token: "${{ secrets.GH_TOKEN }}"
      - name: "remove inital tags"
        uses: andymckay/labeler@master
        if: "${{ github.event.project_card.column_id == '19053081' }}"
        with:
          add-labels: 'Onboarding Phase, Onboarding in Progress'
          remove-labels: 'Application Phase, Initial Review in Progress, Review in Progress, Revisions in Progress,'
          repo-token: "${{ secrets.GH_TOKEN }}"

